### ISSUE TITLE
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'List<dynamic>

### ISSUE THREAD

**Issue by Pablovs97** [flutter-devs/image_gallery#3]
Hi!

I'm getting the following error on the new version of ImageGallery (v1.2.0)

`E/flutter ( 4808): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'List<dynamic>'`
`E/flutter ( 4808): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:13)`
`E/flutter ( 4808): <asynchronous suspension>`
`E/flutter ( 4808): #1      FlutterGallaryPlugin.getAllImages (package:image_gallery/image_gallery.dart:11:33)`
`E/flutter ( 4808): <asynchronous suspension>`

**Comment by Ahmadre** [comment]
also got that error in the past. Make sure your XCode project is configured for swift and got a swift compiler (like 4, 4.2, or 5). Note, that you have to make sure image_gallery is using that version in your podspec!

**Comment by Ahmadre** [comment]
Also try to set in image_gallery.dart the object variables type to __var__

**Comment by preciousome** [comment]
i have the same error
please what do i do

**Comment by rudys-oshin** [comment]
The error is not from the library, is from the example, the vairable 'allImageTemp' has a type list,  but it is an map, the solving is: var allImageTemp instead List allImageTemp.
